services:
  service:
    container_name: msg-service
    build:
      context: .
      dockerfile: Dockerfile.dev
      secrets:
        - netrc
    env_file:
      - ./.env
    secrets:
      - netrc
    networks:
      - service_net
    volumes:
      - ./:/app
networks:
  service_net:
    external: true
secrets:
  netrc:
    file: .netrc
